[package]
name = "bel"
description = "A parser and interpreter for the Better Expression Language (BEL)"
version = "0.11.0"
edition = "2024"
license = "MIT"
categories = ["compilers", "language"]


[features]
default = ["regex", "time", "ip"]
ip = ["dep:ipnetwork"]
json = ["dep:serde_json", "dep:base64"]
regex = ["dep:regex"]
time = ["dep:chrono"]
# arbitrary = ["dep:arbitrary", "chrono?/arbitrary", "chrono?/std"]
# dhat-heap = [ ] # if you are doing heap profiling


[dependencies]
base64 = { path = "../base64", optional = true }
ipnetwork = { path = "../ipnetwork", optional = true, features = ["serde"] }
thiserror = { workspace = true }

antlr4rust = { workspace = true }
nom = { workspace = true }
paste = { workspace = true }
serde = { workspace = true, features = ["derive", "std"] }

arbitrary = { workspace = true, optional = true }
chrono = { workspace = true, optional = true }
regex = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }


[dev-dependencies]
serde_bytes = { workspace = true }
