[package]
name = "template"
version = "0.1.0"
edition = "2024"

[lib]
path = "./template.rs"

[features]
default = ["std"]
std = ["serde/std", "memchr/std"]

[dependencies]
memchr = { version = "2", default-features = false }
serde = { workspace = true, default-features = false, features = ["derive", "alloc"] }
