[package]
name = "format_number"
version = "0.1.0"
edition = "2024"

[lib]
path = "format_number.rs"

[dev-dependencies]
itoa = { workspace = true }
rand = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
criterion = { workspace = true }

[[bench]]
name = "bench"
harness = false
