[package]
name = "tls"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/tls.rs"

[features]
default = ["crypto-default-provider", "webpki-validator", "std"]
crypto-default-provider = ["dep:crypto", "crypto/random"]
std = ["crypto/std"]
tokio = ["dep:tokio", "std"]
webpki-validator = ["dep:rustls-pki-types", "dep:rustls-webpki", "dep:webpki-roots", "dep:x509"]
quic = []
zeroize = ["dep:zeroize"]

[dependencies]
async-trait = "0.1"
bytes = { workspace = true }
constant_time_eq = { path = "../../constant_time_eq" }
crypto = { path = "../../crypto", optional = true, default-features = false }
heapless = { workspace = true }
rustls-pki-types = { version = "1", optional = true }
rustls-webpki = { version = "0.103", default-features = false, features = ["alloc", "ring"], optional = true }
tokio = { workspace = true, optional = true }
webpki-roots = { version = "1", optional = true }
x509 = { path = "../x509", optional = true }
zeroize = { workspace = true, optional = true }

[dev-dependencies]
anyerr = { path = "../../anyerr" }
heapless = { workspace = true }
hex = { path = "../../hex" }
rcgen = "0.13"
rustls = { workspace = true, features = ["std"] }
tokio = { workspace = true, features = ["net", "rt", "io-util", "macros"] }

[[example]]
name = "connect"
required-features = ["std"]

[[example]]
name = "connect_tokio"
required-features = ["tokio"]
