[workspace]
resolver = "2"

members = [
    "acme",
    "anyerr",
    "base32",
    "base64",
    "bel",
    "bel/benchmarks",
    "bel/examples",
    # "bel/fuzz",
    "big_number",
    "constant_time_eq",
    "countries",
    "crc32",
    "cron",
    "crypto",
    "csv",
    "docker",
    "dotenv",
    "dotenv/dotenv_derive",
    "embed",
    "embed/embed_impl",
    "errgroup",
    "embed/embed_utils",
    "form_urlencoded",
    "getopts",
    "hex",
    "hostname",
    "html_escape",
    "httpdate",
    "ipnetwork",
    "json_rpc",
    "jwt",
    "mail_builder",
    "maxminddb",
    "memmem",
    "mime_guess",
    "net",
    "num_cpus",
    "percent_encoding",
    "pin_project_lite",
    "postmark",
    "retry",
    "ryu",
    "s3",
    "scheduler",
    "semver",
    "serde_urlencoded",
    "serde_yaml",
    "single_instance",
    "singleflight",
    "small_collections",
    "strings",
    "template",
    "term",
    "thiserror",
    "thiserror/impl",
    "tld",
    "tokio_fast_udp",
    "tools/crypt",
    "tools/duplicates",
    "tools/energy_bench",
    "unsafe_libyaml",
    "uuid",
    "xxhash",
]

[workspace.dependencies]
anyerr = { path = "anyerr" }
antlr4rust = "=0.3.0-rc2"
arbitrary = { version = "1", features = ["derive"] }
axum = { version = "0.7", default-features = false, features = ["http1", "json", "tokio"] }
blake3 = { default-features = false, git = "https://github.com/BLAKE3-team/BLAKE3", rev = "f3149ec5bb5449af877ba20377a11008ff499fa2" } # 1.8.7
bytes = { version = "1", default-features = false }
chrono = { version = "0.4", default-features = false, features = ["clock", "oldtime", "serde", "std", ] }
futures-util = "0.3"
getrandom = { version = "0.4", default-features = false }
heapless = "0.9"
hyper = { version = "1", features = ["full"] }
indexmap = { version = "2" }
libc = "0.2"
memchr = { version = "2", default-features = false }
mime = "0.3"
nix = { version = "0.31", features = ["socket"] }
nom = "8"
paste = { git = "https://github.com/dtolnay/paste", rev = "6a302522990cbfd9de4e0c61d91854622f7b2999" }
quick-xml = { version = "0.38", features = ["serialize"] }
rand = "0.10"
regex = { version = "1" }
reqwest = { version = "0.13", default-features = false, features = ["charset", "gzip", "http2", "multipart", "json", "rustls", "zstd"] }
serde = { version = "1", default-features = false }
serde_bytes = "0.11"
serde_json = "1"
smallvec = { version = "2.0.0-alpha.12" }
sqlx = { git = "https://github.com/transact-rs/sqlx", rev = "b54008a329541c0ce230d8b203e0c00fc8e8ea48" }
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
unicode-width = "0.1"
url = "2"
walkdir = "2"
zeroize = { version = "1", features = ["simd", "derive"] }


# For macros
syn = { version = "3", default-features = false, features = ["derive", "extra-traits", "parsing", "proc-macro", "printing"] }
quote = "1"
proc-macro2 = "1"

# benchmarks
criterion = { version = "0.8", features = ["html_reports"] }
