[package]
name = "csv"
version = "0.1.0"
edition = "2024"
license = "MIT"

[lib]
path = "./csv.rs"

[features]
default = ["std"]
std = ["serde?/std"]
serde = ["dep:format_number", "dep:ryu", "dep:serde"]

[dependencies]
format_number = { path = "../format_number", optional = true }
memchr = { workspace = true }
ryu = { path = "../ryu", optional = true }
serde = { workspace = true, default-features = false, features = ["derive", "alloc"], optional = true }
