[package]
name = "base32"
version = "0.1.0"
edition = "2024"

[lib]
path = "./base32.rs"

[features]
default = ["std"]
alloc = []
std = ["alloc"]
serde = ["dep:serde"]

[dependencies]
serde = { workspace = true, optional = true }

[dev-dependencies]
rand = { workspace = true }
serde_json = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
criterion = { workspace = true }

[[bench]]
name = "bench"
harness = false
