[package]
name = "embed_utils"
version = "8.4.0"
description = "Utilities for rust-embed"
readme = "readme.md"
documentation = "https://docs.rs/rust-embed"
license = "MIT"
keywords = ["http", "rocket", "static", "web", "server"]
categories = ["web-programming::http-server"]
authors = ["pyros2097 <pyros2097@gmail.com>"]
edition = "2024"


[lib]
path = "./embed_utils.rs"

[dependencies]
crypto = { path = "../../crypto" }
walkdir = { workspace = true }


mime_guess = { path = "../../mime_guess", optional = true }

# [dependencies.globset]
# version = "0.4.8"
# optional = true

[features]
debug-embed = []
mime-guess = ["dep:mime_guess"]
# include-exclude = ["globset"]
