alias gs="git status"
alias ga="git add"
alias gu="git add -u"
alias gm="git commit -m"
alias gp="git push"
alias oc="opencode --standalone"

export TZ="UTC"
export DO_NOT_TRACK=1


export PATH="$PATH:$HOME/.local/bin:$HOME/.cargo/bin:$HOME/.npm/bin"
