[target.wasm32-wasip1]
runner = ".cargo/wasi-runner.sh"

# Using lld as the linker greatly improve compilation times
[target.x86_64-unknown-linux-gnu]
rustflags = ["-Clink-args=-fuse-ld=lld"]

[target.aarch64-unknown-linux-gnu]
rustflags = ["-Clink-args=-fuse-ld=lld"]
