[package]
name = "thiserror"
version = "2.0.21"
authors = ["David Tolnay <dtolnay@gmail.com>"]
categories = ["rust-patterns", "no-std"]
description = "derive(Error)"
edition = "2024"
keywords = ["error", "error-handling", "derive"]
license = "MIT"
rust-version = "1.85"

[features]
default = ["std"]

# Std feature enables support for formatting std types in error messages
std = []

[dependencies]
thiserror_impl = { path = "impl" }

[dev-dependencies]
anyerr = { path = "../anyerr" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
rustdoc-args = [
    "--generate-link-to-definition",
    "--generate-macro-expansion",
    "--extern-html-root-url=core=https://doc.rust-lang.org",
    "--extern-html-root-url=alloc=https://doc.rust-lang.org",
    "--extern-html-root-url=std=https://doc.rust-lang.org",
]
