[package]
name = "bel_examples"
version = "0.1.0"
edition = "2024"

[features]
axum = ["dep:axum", "dep:tokio", "dep:thiserror"]
json = ["dep:serde_json", "bel/json"]
time = ["dep:chrono", "bel/time"]
anyhow = ["dep:anyerr"]
regex = ["bel/regex"]
ip = ["bel/ip"]

[dependencies]
bel = { path = "..", default-features = false }

chrono = { workspace = true, optional = true }

serde = { workspace = true, features = ["derive", "std"] }
serde_json = { workspace = true, optional = true }

axum = { workspace = true, optional = true }
tokio = { workspace = true, optional = true }
thiserror = { workspace = true, optional = true }
anyerr = { workspace = true, optional = true }

[[bin]]
name = "simple"
path = "src/simple.rs"
required-features = ["regex"]

[[bin]]
name = "variables"
path = "src/variables.rs"

[[bin]]
name = "functions"
path = "src/functions.rs"
required-features = ["time"]

[[bin]]
name = "threads"
path = "src/threads.rs"

[[bin]]
name = "serde"
path = "src/serde.rs"

[[bin]]
name = "axum"
path = "src/axum.rs"
required-features = ["axum"]

[[bin]]
name = "json"
path = "src/json.rs"
required-features = ["json"]

[[bin]]
name = "anyhow"
path = "src/anyhow.rs"
required-features = ["anyhow"]


[[bin]]
name = "ip"
path = "src/ip.rs"
required-features = ["ip"]
