[package]
name = "tls2"
version = "0.1.0"
edition = "2024"

[lib]
path = "tls.rs"

[features]
default = ["crypto-default-provider", "default-certificate-verifier", "std", "tokio"]
crypto-default-provider = ["dep:crypto", "crypto/random"]
default-certificate-verifier = ["dep:crypto"]
std = ["crypto/std", "x509/std", "dep:async-trait"]
tokio = ["dep:tokio", "std"]
zeroize = ["dep:zeroize", "crypto?/zeroize"]

[dependencies]
async-trait = { workspace = true, optional = true }
crypto = { path = "../../crypto", optional = true, default-features = false }
heapless = { workspace = true }
tokio = { workspace = true, optional = true }
x509 = { path = "../x509", features = ["std"] }
zeroize = { workspace = true, optional = true }


[[example]]
name = "tokio"
required-features = ["tokio"]
