[package]
name = "small_collections"
version = "0.1.0"
edition = "2024"

[lib]
path = "small_collections.rs"


[features]
default = ["std"]

bytes = ["dep:bytes"]
serde = ["dep:serde", "serde/alloc"]
std = ["serde?/std"]

[dependencies]
bytes = { workspace = true, optional = true }
serde = { workspace = true, optional = true, default-features = false }
heapless = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
