name: Benchmarks

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  benchmarks_native:
    strategy:
      fail-fast: false
      matrix:
        runner: [ubuntu-latest, ubuntu-24.04-arm]
    runs-on: ${{ matrix.runner }}
    env:
      RUSTFLAGS: "-C target-cpu=native"
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: recursive
      - run: cat /proc/cpuinfo
      - run: sudo apt-get update && sudo apt upgrade && sudo apt-get install -y clang lld
      - run: rustup update stable
      - run: cargo bench -p crypto
      - run: cargo bench -p xxhash
