name: Benchmarks

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  crypto_benchmark:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    env:
      RUSTFLAGS: "-C linker=gcc"
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: recursive
      - run: rustup update stable
      - run: RUSTFLAGS="-C target-cpu=native" cargo bench --package crypto


  checksum_benchmark:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    env:
      RUSTFLAGS: "-C linker=gcc"
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: recursive
      - run: rustup update stable
      - run: RUSTFLAGS="-C target-cpu=native" cargo bench --package xxhash

  format_numbers:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    env:
      RUSTFLAGS: "-C linker=gcc"
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: recursive
      - run: rustup update stable
      - run: RUSTFLAGS="-C target-cpu=native" cargo bench --package format_number
