name: Benchmarks

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  benchmarks_native:
    strategy:
      fail-fast: false
      matrix:
        runner: [ubuntu-latest, ubuntu-24.04-arm]
    runs-on: ${{ matrix.runner }}
    env:
      RUSTFLAGS: "-C target-cpu=native"
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: recursive
      - run: sudo apt-get update && sudo apt upgrade && sudo apt-get install -y clang lld
      - run: sudo apt-get update && sudo apt upgrade && sudo apt-get install -y clang lld
      - run: rustup update stable
      - run: cargo bench -p crypto
      - run: cargo bench -p xxhash
      - run: cargo bench -p format_number

  benchmarks_wasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: recursive
      - run: sudo apt-get update && sudo apt upgrade && sudo apt-get install -y clang lld
      # curl and xz-utils are needed to install wasmtime
      - run: sudo apt-get update && sudo apt upgrade && sudo apt-get install -y clang lld curl xz-utils
      - run: rustup update stable
      - run: rustup target add wasm32-wasip1
      - run: |
          curl https://wasmtime.dev/install.sh -sSf | bash
          echo "$HOME/.wasmtime/bin" >> $GITHUB_PATH
      - run: RUSTFLAGS="-C target-feature=+simd128" cargo run --target=wasm32-wasip1 -p wasm_benchmarks_crypto
