name: CI

on:
  push:
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-24.04-arm
          - target: wasm32-wasip1
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: recursive
      - run: sudo apt-get update && sudo apt upgrade && sudo apt-get install -y clang lld
      - run: rustup update stable
      - if: matrix.target == 'wasm32-wasip1'
        run: rustup target add wasm32-wasip1
      - if: matrix.target != 'wasm32-wasip1'
        run: make check
      # package that run on all platforms
      - run: cargo test --target ${{ matrix.target }} -p hex -p base64 -p base32 -p crypto

